services:
  stealallthecats:
    container_name: stealallthecats
    build:
      context: .
      dockerfile: StealAllTheCats/Dockerfile
    image: stealallthecats:latest  # explicitly tag your local built image
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=CatsDb;User Id=sa;Password=Strong@Password123;TrustServerCertificate=True

  db:
    container_name: stealallthecats_db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      MSSQL_SA_PASSWORD: "Strong@Password123"
      ACCEPT_EULA: "Y"
    volumes:
      - catdb-data:/var/opt/mssql

volumes:
  catdb-data: